/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RegisterClassSubjectsDialog.java
 *
 * Created on Dec 13, 2013, 11:22:36 AM
 */
package vpssmsclient;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import vpssmsserver.ClassSubjectRegister;
import vpssmsserver.StudentClass;
import vpssmsserver.SubjectRegister;

/**
 *
 * @author Royal
 */
public class RegisterClassSubjectsDialog extends javax.swing.JDialog {

    private ArrayList<SubjectRegister> subjectRegisterList;
    private ArrayList<StudentClass> classList;

    /** Creates new form RegisterClassSubjectsDialog */
    public RegisterClassSubjectsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            classList = new Controller().getStudentClassList();
            subjectRegisterList = new Controller().getSubjectRegisterList();
            if (!(classList.isEmpty())) {
                for (int i = 0; i < classList.size(); i++) {
                    studentClass.addItem(classList.get(i).getName());
                }

            }
            if (!(subjectRegisterList.isEmpty())) {
                for (int i = 0; i < subjectRegisterList.size(); i++) {
                    register.addItem(subjectRegisterList.get(i).getName());
                }

            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        studentClass = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        register = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        term = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        year = new com.toedter.calendar.JYearChooser();
        registerSubject = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Class");

        studentClass.setFont(new java.awt.Font("Times New Roman", 1, 18));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Subject Register");

        register.setFont(new java.awt.Font("Times New Roman", 1, 18));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Term");

        term.setFont(new java.awt.Font("Times New Roman", 1, 18));
        term.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Term 1", "Term 2", "Term 3" }));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Academic Year");

        year.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        year.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        registerSubject.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        registerSubject.setText("Register");
        registerSubject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerSubjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(year, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(register, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(term, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(studentClass, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(registerSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {register, studentClass, term, year});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(studentClass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(term, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addComponent(registerSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {register, studentClass, term, year});

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void registerSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerSubjectActionPerformed
// TODO add your handling code here:
    try{
        boolean added=new Controller().registerClassSubjects(new ClassSubjectRegister(
                new Controller().generateId(),
                classList.get(studentClass.getSelectedIndex()).getClassId(),
                subjectRegisterList.get(register.getSelectedIndex()).getRegisterId(),
                term.getSelectedItem().toString(),
                Integer.toString(year.getYear())
                ));
        if(added==true){
            JOptionPane.showMessageDialog(this, "Class Subjects Registered Successfully");
            ClassSubjectsRegisterWindow.ClassSubjectRegisterTable.setModel(new Controller().classSubjectRegisterTableModel());
        }else{
        JOptionPane.showMessageDialog(this, "ERROR \n Class Subjects \n NOT \nRegistered. Please try again");
        }
    
    }catch(Exception ex){
        System.out.println(ex.getMessage());
    }
}//GEN-LAST:event_registerSubjectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterClassSubjectsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterClassSubjectsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterClassSubjectsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterClassSubjectsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                RegisterClassSubjectsDialog dialog = new RegisterClassSubjectsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox register;
    private javax.swing.JButton registerSubject;
    private javax.swing.JComboBox studentClass;
    private javax.swing.JComboBox term;
    private com.toedter.calendar.JYearChooser year;
    // End of variables declaration//GEN-END:variables
}
