/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TaskSelectionMenu.java
 *
 * Created on Dec 6, 2013, 10:17:53 PM
 */
package vpssmsclient;

/**
 *
 * @author Royal
 */
public class TaskSelectionMenu extends javax.swing.JPanel {

    /** Creates new form TaskSelectionMenu */
    public TaskSelectionMenu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        registerNewStudent = new javax.swing.JButton();
        registerOldStudent = new javax.swing.JButton();
        createClassStream = new javax.swing.JButton();
        registerClassSubjects = new javax.swing.JButton();
        registerSubjectPapers = new javax.swing.JButton();
        enterStudentResults = new javax.swing.JButton();

        setOpaque(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vpssmsclient/Images/computer.jpg"))); // NOI18N

        registerNewStudent.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        registerNewStudent.setText("Register New Student");
        registerNewStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerNewStudentActionPerformed(evt);
            }
        });

        registerOldStudent.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        registerOldStudent.setText("Register Continuing Student");
        registerOldStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerOldStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerOldStudentActionPerformed(evt);
            }
        });

        createClassStream.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        createClassStream.setText("Create Classes & Streams");
        createClassStream.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createClassStream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createClassStreamActionPerformed(evt);
            }
        });

        registerClassSubjects.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        registerClassSubjects.setText("Register Class Subjects");
        registerClassSubjects.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerClassSubjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerClassSubjectsActionPerformed(evt);
            }
        });

        registerSubjectPapers.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        registerSubjectPapers.setText("Register Subjects\n& its Papers");
        registerSubjectPapers.setAutoscrolls(true);
        registerSubjectPapers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerSubjectPapers.setOpaque(false);
        registerSubjectPapers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerSubjectPapersActionPerformed(evt);
            }
        });

        enterStudentResults.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        enterStudentResults.setText("Enter Results");
        enterStudentResults.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enterStudentResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterStudentResultsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerNewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createClassStream, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerSubjectPapers))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterStudentResults)
                    .addComponent(registerClassSubjects)
                    .addComponent(registerOldStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(175, 175, 175))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {createClassStream, enterStudentResults, registerClassSubjects, registerNewStudent, registerOldStudent, registerSubjectPapers});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registerNewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerOldStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createClassStream, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerClassSubjects))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerSubjectPapers)
                            .addComponent(enterStudentResults)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {createClassStream, enterStudentResults, registerClassSubjects, registerNewStudent, registerOldStudent, registerSubjectPapers});

    }// </editor-fold>//GEN-END:initComponents

private void registerSubjectPapersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerSubjectPapersActionPerformed
// TODO add your handling code here:
    try{
        VPSSMSClient.mainWindow.setContentPane(new SubjectPaperRegistrationWindow());
        VPSSMSClient.mainWindow.setVisible(true);
    }catch(Exception ex){
    System.out.println(ex.getMessage());
    }
}//GEN-LAST:event_registerSubjectPapersActionPerformed

private void registerNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerNewStudentActionPerformed
// TODO add your handling code here:
    try{
        VPSSMSClient.mainWindow.setContentPane(new StudentRegistrationWindow());
        VPSSMSClient.mainWindow.setVisible(true);
    }catch(Exception ex){
    System.out.println(ex.getMessage());
    }
}//GEN-LAST:event_registerNewStudentActionPerformed

private void registerOldStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerOldStudentActionPerformed
// TODO add your handling code here:
    try{
        VPSSMSClient.mainWindow.setContentPane(new RegisterOldStudentWindow());
        VPSSMSClient.mainWindow.setVisible(true);
    }catch(Exception ex){
    System.out.println(ex.getMessage());
    }
}//GEN-LAST:event_registerOldStudentActionPerformed

private void createClassStreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createClassStreamActionPerformed
// TODO add your handling code here:
    try{
        VPSSMSClient.mainWindow.setContentPane(new ClassStreamCategoryWindow());
        VPSSMSClient.mainWindow.setVisible(true);
    }catch(Exception ex){
    System.out.println(ex.getMessage());
    }
}//GEN-LAST:event_createClassStreamActionPerformed

private void registerClassSubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerClassSubjectsActionPerformed
// TODO add your handling code here:
    try{
        VPSSMSClient.mainWindow.setContentPane(new ClassSubjectsRegisterWindow());
        VPSSMSClient.mainWindow.setVisible(true);
    }catch(Exception ex){
    System.out.println(ex.getMessage());
    }
}//GEN-LAST:event_registerClassSubjectsActionPerformed

private void enterStudentResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterStudentResultsActionPerformed
// TODO add your handling code here:
    try{
        VPSSMSClient.mainWindow.setContentPane(new EnterResultsWindow());
        VPSSMSClient.mainWindow.setVisible(true);
    }catch(Exception ex){
    System.out.println(ex.getMessage());
    }
}//GEN-LAST:event_enterStudentResultsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createClassStream;
    private javax.swing.JButton enterStudentResults;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton registerClassSubjects;
    private javax.swing.JButton registerNewStudent;
    private javax.swing.JButton registerOldStudent;
    private javax.swing.JButton registerSubjectPapers;
    // End of variables declaration//GEN-END:variables
}
